name: Build macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-13
    steps:
    - name: Force Xcode 14.3
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app
    - name: List Xcodes
      run: ls /Applications | grep Xcode
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: brew install pkg-config gtk4
    - name: Debug
      run: |
        pkg-config --libs gtk4
        which pkg-config
        brew --version
        pkg-config --cflags libffi
        mv /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk.orig
    - name: Patch libffi
      run: |
        echo "exec_prefix=/usr
libdir=${exec_prefix}/lib
toolexeclibdir=${libdir}

Name: libffi
Description: Library supporting Foreign Function Interfaces
Version: 3.4-rc1
Libs: -L${toolexeclibdir} -lffi
Cflags: " > /opt/homebrew/Library/Homebrew/os/mac/pkgconfig/13/libffi.pc
    - name: Build
      run: swift build -v
