name: Build macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-12
    steps:
    - name: Force Xcode 13.2
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app
    - name: List Xcodes
      run: ls /Applications | grep Xcode
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: brew install gtk4
    - name: Build
      run: swift build -v
