name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: brew install gtk+3
    - name: Build
      run: swift build -v
    #- name: Run tests
      #run: swift test -v

  build-linux:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
      # If you'd rather use a certain version, format it like this: (5.6 is the latest as of writing)
      #- uses: fwal/setup-swift@v1
        #with:
          #swift-version: "5.6.0"
      - name: Install Dependencies
        run: |
          sudo apt update && \
          sudo apt install -y libgtk-3-dev clang
      - name: Build
        run: swift build -v
      #- name: Run tests
        #run: swift test -v